set nocompatible              " be iMproved, required
filetype off                  " required
" setlocal fo+=aw
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.jpg     " MacOSX/Linux
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')
"
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" PLUGINS "
" base
"
Plugin 'mileszs/ack.vim'
Plugin 'ervandew/supertab'
Plugin 'fholgado/minibufexpl.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
" Plugin 'majutsushi/tagbar'
" csv
Plugin 'chrisbra/csv.vim'
" color
Plugin 'altercation/vim-colors-solarized'

" coding
" Plugin 'kchmck/vim-coffee-script'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'nicklasos/vim-jsx-riot'
" Plugin 'godlygeek/tabular'
" Plugin 'plasticboy/vim-markdown'
Plugin 'groenewege/vim-less'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'tpope/vim-surround.git'
Plugin 'tpope/vim-commentary'
Plugin 'Raimondi/delimitMate'
Plugin 'scrooloose/syntastic'

" R
Plugin 'vim-scripts/Vim-R-plugin'
" Plugin 'ervandew/screen'

" python
Plugin 'davidhalter/jedi-vim'
Plugin 'tell-k/vim-autopep8'

" jinja2
Plugin 'Glench/Vim-Jinja2-Syntax'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set hidden

" enable syntax highlighting
syntax enable

" No menus, scrollbars, or other junk
set guioptions=

" Disable backup and swap files
set nobackup
set noswapfile

" Automatically load changed files
set autoread

" allow the cursor to pass the last character
set virtualedit=onemore

" show line numbers
set number

" Case insensitive search
set ignorecase
" Case sensitive if we type an uppercase
set smartcase


" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent
set smartindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line
set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1

" set spell

" SPLITS
" https://robots.thoughtbot.com/vim-splits-move-faster-and-more-naturally
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set splitbelow
set splitright

" color
set background=dark
set t_Co=16
let g:solarized_termcolors=16
colorscheme solarized

" powerline
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set guifont=Meslo\ LG\ S\ DZ\ for\ Powerline
set laststatus=2

" TAGBAR
" mapping
nmap <F9> :TagbarToggle<CR>

" SOURCE
source ~/.vim/conf/autocomplete
source ~/.vim/conf/syntastic
source ~/.vim/conf/keybindings
source ~/.vim/conf/idesettings
